# docker-compose.yml

version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - user-service-db:/var/lib/postgresql/data

  user-service:
    build:
      context: .
    environment:
      JWT_SECRET: 123
      PASSWORD_SALT: 123
      PORT: 3000
      DATABASE_URL: postgresql://postgres:password@postgres
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  user-service-db:
